bmirobot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1
    pid: {p: 10.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_2
    pid: {p: 10.0, i: 0.01, d: 10.0}
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_3
    pid: {p: 10.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_4
    pid: {p: 10.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_5
    pid: {p: 10.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_6
    pid: {p: 10.0, i: 0.01, d: 10.0}
  joint7_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_7
    pid: {p: 10.0, i: 0.01, d: 10.0}


  cart_controller:
    type: position_controllers/BmirobotControlCart
    root_name: base_link
    tip_name: link8
    k_posture: 25.0
    jacobian_inverse_damping: 0.01
    pose_command_filter: 0.01
    fb_trans:
      p: 2.5
      i: 0.35
      d: 0.0
      i_clamp: 0.3
    fb_rot:
      p: 0.15
      i: 0.03
      d: 0.0
      i_clamp: 0.06
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7



  right_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7

  left_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7


  # Position Controllers ---------------------------------------
  right_group_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7

  left_group_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7




  right_group_hand_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - right_hand_joint1
      - right_hand_joint2

  left_group_hand_controller:
    type: position_controllers/JointGroupPositionController
    joints:
      - left_hand_joint1
      - left_hand_joint2


