controller_list:
  - name: fake_arm1_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7
  - name: fake_grasp1_controller
    joints:
      - joint7
      - hand_joint_1
      - hand_joint_4